spring:
  # redis 配置
  redis:
    host: ${qqbot.redis.host}
    port: ${qqbot.redis.port}
    database: ${qqbot.redis.database}
    password: ${qqbot.redis.password}

  # oss
  cloud:
    alicloud:
      access-key: ${qqbot.alicloud.oss.access-key}
      secret-key: ${qqbot.alicloud.oss.secret-key}
      oss:
        endpoint: ${qqbot.alicloud.oss.endpoint}

  #邮件发送配置
  mail:
    username: ${qqbot.email.username}
    password: ${qqbot.email.password}
    host: smtp.qq.com
    # 开启加密授权验证
    properties:
      mail:
        smtp:
          ssl:
            enable:
              true

  main:
    # 允许重载 bean
    allow-bean-definition-overriding: true

shiro:
  plugin-list:
    - com.yixihan.yibot.plugin.PokePlugin
    - com.yixihan.yibot.plugin.AutoRemindPlugin

management:
  endpoints:
    web:
      exposure:
        include: "*" # 开放所有端点 默认值只打开 health 和 info 两个端点
  endpoint:
    # health 端点配置项
    health:
      enabled: true
      show-details: always # 永远展示完整信息
